name: dotnet5_asp
description: App Description
ignoreFiles: .git bin obj
modules:
- name: template
  language: dotnetcore5.0
  web: asp
  projectFolder: /dotnet5_asp.template
  description: Module description
  functions:
  - name: Startup
    entry: Startup.cs
    description: the entry point for the function